<?php
declare(strict_types=1);
namespace MarketForecast\Tests;
use MarketForecast\AI\{ForecastPairRepository,OpenAIProvider,PairedForecastOrchestrator};
use MarketForecast\Database\{Connection,Migrator};
use MarketForecast\Evaluation\ForecastTargetRepository;
use MarketForecast\Forecast\{ForecastFreezer,QuantForecastEngine};
use PHPUnit\Framework\TestCase;
final class PairedForecastOrchestratorTest extends TestCase
{
 public function testPersistsIndependentPredictionsFinalsAndPair():void{$p=tempnam(sys_get_temp_dir(),'pair-e2e-');$db=Connection::open($p);(new Migrator($db))->apply(dirname(__DIR__).'/database/migrations','now');$db->exec("INSERT INTO experiments(experiment_code,name,description,start_at,status,config_json) VALUES('E','E','E','now','ACTIVE','{}');INSERT INTO forecast_runs(experiment_id,run_key,scheduled_for,status,state_detail,information_cutoff) VALUES(1,'r','now','RUNNING','CREATED','2026-09-11T00:00:00Z');INSERT INTO assets(symbol,display_name,asset_type,provider,provider_symbol,timezone) VALUES('T','T','STOCK','TEST','T','UTC');INSERT INTO market_snapshots(experiment_id,asset_id,information_cutoff,snapshot_time,features_json,source_data_hash,feature_set_version,feature_snapshot_hash,market_data_fingerprint,market_bar_count) VALUES(1,1,'2026-09-11T00:00:00Z','now','{}','m','FEATURE_SET_V1','f','m',1);");$ai=new OpenAIProvider('test','test','https://invalid',fn()=>['output_text'=>'{"direction":"BULLISH","probability_up":0.7,"probability_neutral":0.2,"probability_down":0.1,"expected_return_pct":1.2,"confidence":0.7,"reason_codes":["POSITIVE_TREND"],"explanation":"fixture"}']);$o=new PairedForecastOrchestrator($db,new QuantForecastEngine(),$ai,new ForecastPairRepository($db),new ForecastFreezer());$features=['close'=>110,'sma20'=>108,'sma50'=>105,'ema20'=>109,'ema50'=>106,'rsi14'=>60,'atr14'=>2,'momentum5'=>2,'momentum20'=>4];$r=$o->run(1,1,1,'1D','2026-09-11T00:00:00Z',1,'f',$features,100,'2026-09-11T00:00:00Z');self::assertNotNull($r['pair_id']);self::assertSame(2,(int)$db->query('SELECT COUNT(*) FROM final_predictions WHERE forecast_pair_id='.$r['pair_id'])->fetchColumn());}
 public function testCryptoPairAndTargetsPersistInsideProductionTransaction():void{$p=tempnam(sys_get_temp_dir(),'pair-crypto-');$db=Connection::open($p);(new Migrator($db))->apply(dirname(__DIR__).'/database/migrations','now');$db->exec("INSERT INTO experiments(experiment_code,name,description,start_at,status,config_json) VALUES('E','E','E','now','ACTIVE','{}');INSERT INTO forecast_runs(experiment_id,run_key,scheduled_for,status,state_detail,information_cutoff) VALUES(1,'crypto-r','now','RUNNING','CREATED','2026-09-15T20:25:00Z');INSERT INTO assets(symbol,display_name,asset_type,provider,provider_symbol,timezone,is_24_7) VALUES('BTC/USD','BTC','CRYPTO','ALPACA','BTC/USD','UTC',1);INSERT INTO market_snapshots(experiment_id,asset_id,information_cutoff,snapshot_time,features_json,source_data_hash,feature_set_version,feature_snapshot_hash,market_data_fingerprint,market_bar_count) VALUES(1,1,'2026-09-15T20:25:00Z','now','{}','m','FEATURE_SET_V1','f','m',60);");$ai=new OpenAIProvider('test','test','https://invalid',fn()=>['output_text'=>'{"direction":"BULLISH","probability_up":0.7,"probability_neutral":0.2,"probability_down":0.1,"expected_return_pct":1.2,"confidence":0.7,"reason_codes":["POSITIVE_TREND"],"explanation":"fixture"}']);$o=new PairedForecastOrchestrator($db,new QuantForecastEngine(),$ai,new ForecastPairRepository($db),new ForecastFreezer());$features=['close'=>110,'sma20'=>108,'sma50'=>105,'ema20'=>109,'ema50'=>106,'rsi14'=>60,'atr14'=>2,'momentum5'=>2,'momentum20'=>4];$db->beginTransaction();$r=$o->run(1,1,1,'24H','2026-09-15T20:25:00Z',1,'f',$features,100,'2026-09-15T20:25:00Z');$targets=new ForecastTargetRepository($db);$targets->create($r['quant_final_id'],'CRYPTO',new \DateTimeImmutable('2026-09-15T20:25:00Z'),'24H');$targets->create($r['ai_final_id'],'CRYPTO',new \DateTimeImmutable('2026-09-15T20:25:00Z'),'24H');$db->commit();self::assertSame(2,(int)$db->query('SELECT COUNT(*) FROM forecast_targets')->fetchColumn());self::assertSame(0,(int)$db->query('PRAGMA foreign_key_check')->fetchColumn());}
}
