<?php
declare(strict_types=1);
namespace MarketForecast\MarketData;
use DateTimeImmutable;use DateTimeInterface;use RuntimeException;
final class AlpacaProvider implements MarketDataProviderInterface
{
 public function __construct(private readonly string $baseUrl,private readonly string $apiKey,private readonly string $apiSecret,private readonly int $timeoutSeconds=15,private readonly int $maxAttempts=3){}
 public function getHistoricalBars(string $symbol,string $timeframe,DateTimeImmutable $start,DateTimeImmutable $end):array{$crypto=str_contains($symbol,'/');$path=$crypto?'/v1beta3/crypto/us/bars':'/v2/stocks/'.rawurlencode($symbol).'/bars';$query=$crypto?['symbols'=>$symbol,'timeframe'=>$timeframe,'start'=>$start->format(DateTimeInterface::ATOM),'end'=>$end->format(DateTimeInterface::ATOM),'limit'=>'10000']:['timeframe'=>$timeframe,'start'=>$start->format(DateTimeInterface::ATOM),'end'=>$end->format(DateTimeInterface::ATOM),'limit'=>'10000','feed'=>'iex'];$all=[];$token=null;do{if($token!==null)$query['page_token']=$token;$response=$this->request($path,$query);$rows=$crypto?($response['bars'][$symbol]??[]):($response['bars']??[]);$all=array_merge($all,$rows);$token=$response['next_page_token']??null;}while(is_string($token)&&$token!=='');return array_values(array_map(fn(array $bar):array=>$this->normalizeBar($bar),$all));}
 public function getLatestValidatedPrice(string $symbol,DateTimeImmutable $notAfter):array{$crypto=str_contains($symbol,'/');$response=$this->request($crypto?'/v1beta3/crypto/us/latest/bars':'/v2/stocks/'.rawurlencode($symbol).'/bars/latest',$crypto?['symbols'=>$symbol]:['feed'=>'iex']);$bar=$crypto?($response['bars'][$symbol]??null):($response['bar']??null);if(!is_array($bar))throw new RuntimeException('No validated latest bar returned.');$n=$this->normalizeBar($bar);if(new DateTimeImmutable($n['time'])>$notAfter)throw new RuntimeException('Latest bar is after cutoff.');return $n;}
 public function healthCheck():bool{try{$this->request('/v2/stocks/SPY/bars/latest',['feed'=>'iex']);return true;}catch(\Throwable){return false;}}
 private function normalizeBar(array $bar):array{foreach(['t','o','h','l','c','v'] as $key)if(!array_key_exists($key,$bar))throw new RuntimeException('Malformed Alpaca bar.');return ['time'=>(new DateTimeImmutable((string)$bar['t']))->format(DateTimeInterface::ATOM),'open'=>(float)$bar['o'],'high'=>(float)$bar['h'],'low'=>(float)$bar['l'],'close'=>(float)$bar['c'],'volume'=>(float)$bar['v'],'provider'=>'ALPACA'];}
 private function request(string $path,array $query):array{$last='';for($attempt=1;$attempt<=$this->maxAttempts;$attempt++){$url=rtrim($this->baseUrl,'/').$path.'?'.http_build_query($query);$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>$this->timeoutSeconds,CURLOPT_HTTPHEADER=>['APCA-API-KEY-ID: '.$this->apiKey,'APCA-API-SECRET-KEY: '.$this->apiSecret,'Accept: application/json']]);$body=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$error=curl_error($ch);curl_close($ch);if($body!==false&&$error===''&&$status>=200&&$status<300){$decoded=json_decode((string)$body,true);if(!is_array($decoded))throw new RuntimeException('Invalid Alpaca JSON.');return $decoded;}$last='HTTP '.$status.($error!==''?': '.$error:'');if($attempt<$this->maxAttempts&&($status===429||$status>=500||$body===false))usleep(250000*$attempt);}
 throw new RuntimeException('Alpaca request failed: '.$last);}
}
