<?php
declare(strict_types=1);
namespace MarketForecast\AI;
use PDO;
final class ForecastPairRepository
{
 public function __construct(private readonly PDO $pdo){}
 public function create(array $pair):int
 { $s=$this->pdo->prepare('INSERT OR IGNORE INTO forecast_pairs(experiment_id,asset_id,horizon_code,forecast_cycle_id,information_cutoff,market_snapshot_id,feature_snapshot_hash,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$pair['experiment_id'],$pair['asset_id'],$pair['horizon_code'],$pair['forecast_cycle_id'],$pair['information_cutoff'],$pair['market_snapshot_id'],$pair['feature_snapshot_hash'],$pair['status']??'OPEN',$pair['created_at']]);$row=$this->pdo->prepare('SELECT * FROM forecast_pairs WHERE experiment_id=? AND asset_id=? AND horizon_code=? AND forecast_cycle_id=?');$row->execute([$pair['experiment_id'],$pair['asset_id'],$pair['horizon_code'],$pair['forecast_cycle_id']]);$found=$row->fetch(PDO::FETCH_ASSOC);if(!$found)throw new \RuntimeException('Unable to create forecast pair.');foreach(['information_cutoff','market_snapshot_id','feature_snapshot_hash'] as $k)if((string)$found[$k] !== (string)$pair[$k])throw new \RuntimeException('Forecast pair identity conflict.');return (int)$found['id'];}
 public function link(int $pairId,int $quantFinalId,int $aiFinalId):void
 {if($quantFinalId===$aiFinalId)throw new \RuntimeException('A pair requires independent predictions.');$q=$this->pdo->prepare('SELECT experiment_id,asset_id,horizon_code,information_cutoff FROM final_predictions WHERE id=? AND source_type=?');$q->execute([$quantFinalId,'QUANT']);$quant=$q->fetch(PDO::FETCH_ASSOC);$q->execute([$aiFinalId,'AI']);$ai=$q->fetch(PDO::FETCH_ASSOC);if(!$quant||!$ai)throw new \RuntimeException('Both QUANT and AI final predictions are required.');foreach(['experiment_id','asset_id','horizon_code','information_cutoff'] as $k)if((string)$quant[$k]!==(string)$ai[$k])throw new \RuntimeException('Paired prediction identity mismatch.');$p=$this->pdo->prepare('SELECT experiment_id,asset_id,horizon_code,information_cutoff FROM forecast_pairs WHERE id=?');$p->execute([$pairId]);$pair=$p->fetch(PDO::FETCH_ASSOC);if(!$pair)throw new \RuntimeException('Pair not found.');foreach(['experiment_id','asset_id','horizon_code','information_cutoff'] as $k)if((string)$pair[$k]!==(string)$quant[$k])throw new \RuntimeException('Pair identity mismatch.');$u=$this->pdo->prepare('UPDATE final_predictions SET forecast_pair_id=? WHERE id IN (?,?) AND forecast_pair_id IS NULL');$u->execute([$pairId,$quantFinalId,$aiFinalId]);if($u->rowCount()!==2)throw new \RuntimeException('Prediction pair link conflict.');}
}
