<?php
declare(strict_types=1);
namespace MarketForecast\AI;
use PDO;
use MarketForecast\Forecast\{QuantForecastEngine,ForecastFreezer};
final class PairedForecastOrchestrator
{
 public function __construct(private readonly PDO $pdo,private readonly QuantForecastEngine $quant,private readonly OpenAIProvider $ai,private readonly ForecastPairRepository $pairs,private readonly ForecastFreezer $freezer){}
 public function run(int $experimentId,int $runId,int $assetId,string $horizon,string $cutoff,int $snapshotId,string $featureHash,array $features,float $referencePrice,string $referenceTime):array
 { $q=$this->quant->predict($features);$qid=$this->saveModel($runId,$assetId,$horizon,'QUANT',$q,$cutoff,$snapshotId,$featureHash,$features);try{$a=$this->ai->forecast($features,$cutoff);$aid=$this->saveModel($runId,$assetId,$horizon,'AI',$a,$cutoff,$snapshotId,$featureHash,$features);}catch(\Throwable $e){$this->pdo->prepare("INSERT INTO system_events(severity,event_type,message,metadata_json,created_at) VALUES('WARNING','AI_PAIRED_CYCLE_FAILED',?,?,?)")->execute(['AI failed; paired cycle rolled back',json_encode(['run_id'=>$runId,'asset_id'=>$assetId,'horizon'=>$horizon,'snapshot_id'=>$snapshotId]),gmdate('c')]);throw new \RuntimeException('AI paired cycle failed; no FINAL prediction was created: '.substr($e->getMessage(),0,160),0,$e);}$qfinal=$this->finalize($experimentId,$runId,$assetId,$horizon,$qid,'QUANT',$q,$cutoff,$referencePrice,$referenceTime);$afinal=$this->finalize($experimentId,$runId,$assetId,$horizon,$aid,'AI',$a,$cutoff,$referencePrice,$referenceTime);$pair=$this->pairs->create(['experiment_id'=>$experimentId,'asset_id'=>$assetId,'horizon_code'=>$horizon,'forecast_cycle_id'=>(string)$runId,'information_cutoff'=>$cutoff,'market_snapshot_id'=>$snapshotId,'feature_snapshot_hash'=>$featureHash,'created_at'=>gmdate('c')]);$this->pairs->link($pair,$qfinal,$afinal);return ['quant_prediction_id'=>$qid,'ai_prediction_id'=>$aid,'quant_final_id'=>$qfinal,'ai_final_id'=>$afinal,'pair_id'=>$pair]; }
 private function saveModel(int $runId,int $assetId,string $horizon,string $source,array $p,string $cutoff,int $snapshotId,string $featureHash,array $features):int{$probs=json_encode([$p['probability_up'],$p['probability_neutral'],$p['probability_down']],JSON_THROW_ON_ERROR);if($source==='QUANT'){$s=$this->pdo->prepare('INSERT OR IGNORE INTO quant_predictions(run_id,asset_id,horizon_code,direction,probabilities_json,expected_return_pct,confidence,features_json,algorithm_version,information_cutoff,market_snapshot_id,feature_snapshot_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$runId,$assetId,$horizon,$p['direction'],$probs,null,$p['confidence'],json_encode($features,JSON_THROW_ON_ERROR),'QUANT_V1',$cutoff,$snapshotId,$featureHash]);}else{$s=$this->pdo->prepare('INSERT OR IGNORE INTO ai_predictions(run_id,asset_id,horizon_code,direction,probabilities_json,expected_return_pct,confidence,reason_codes_json,explanation,raw_response_hash,information_cutoff,market_snapshot_id,feature_snapshot_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$runId,$assetId,$horizon,$p['direction'],$probs,$p['expected_return_pct'],$p['confidence'],json_encode($p['reason_codes'],JSON_THROW_ON_ERROR),$p['explanation'],hash('sha256',json_encode($p,JSON_THROW_ON_ERROR)),$cutoff,$snapshotId,$featureHash]);}if($this->pdo->lastInsertId()!=='0')return (int)$this->pdo->lastInsertId();$table=$source==='QUANT'?'quant_predictions':'ai_predictions';$q=$this->pdo->prepare("SELECT id FROM {$table} WHERE run_id=? AND asset_id=? AND horizon_code=? AND information_cutoff=? AND market_snapshot_id=? AND feature_snapshot_hash=?");$q->execute([$runId,$assetId,$horizon,$cutoff,$snapshotId,$featureHash]);$id=(int)$q->fetchColumn();if($id<=0)throw new \RuntimeException('Unable to persist immutable '.$source.' prediction.');return $id;}
 private function finalize(int $experimentId,int $runId,int $assetId,string $horizon,int $sourceId,string $source,array $p,string $cutoff,float $referencePrice,string $referenceTime):int{$probs=json_encode([$p['probability_up'],$p['probability_neutral'],$p['probability_down']],JSON_THROW_ON_ERROR);$x=$this->freezer->freeze(['experiment_id'=>$experimentId,'run_id'=>$runId,'asset_id'=>$assetId,'source_type'=>$source,'source_prediction_id'=>$sourceId,'horizon_code'=>$horizon,'information_cutoff'=>$cutoff,'generated_at'=>gmdate('c'),'reference_price'=>$referencePrice,'reference_price_time'=>$referenceTime,'direction'=>$p['direction'],'probabilities_json'=>$probs,'expected_return_pct'=>$source==='QUANT'?null:$p['expected_return_pct'],'confidence'=>$p['confidence'],'status'=>'DRAFT']);$hash=$x['forecast_hash'];unset($x['forecast_hash']);$cols=implode(',',array_keys($x)).',forecast_hash';$marks=implode(',',array_fill(0,count($x),'?')).',?';$this->pdo->prepare("INSERT INTO final_predictions($cols) VALUES($marks)")->execute([...array_values($x),$hash]);return (int)$this->pdo->lastInsertId();}
}
