<?php
declare(strict_types=1);
namespace MarketForecast\Jobs;
final class JobState { public const CREATED='CREATED',MARKET_DATA_READY='MARKET_DATA_READY',FEATURES_READY='FEATURES_READY',QUANT_READY='QUANT_READY',AI_READY='AI_READY',VALIDATED='VALIDATED',FINALIZED='FINALIZED',FAILED='FAILED'; }
